name = "doyled-it"
main = "worker/index.js"
compatibility_date = "2026-04-29"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./_site"
binding = "ASSETS"
run_worker_first = [ "/card/chat" ]

[vars]
CARD_CHAT_DISABLED = "false"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "c407eee5592549e194ad8c2b4ee04698"
