export default {
  AB: "At Bats — official plate appearances (excludes walks, HBP, sacrifices)",
  H: "Hits — times reaching base safely via hit",
  "2B": "Doubles — two-base hits",
  "3B": "Triples — three-base hits",
  HR: "Home Runs — four-base hits",
  RBI: "Runs Batted In — runs scored as a result of your hit/action",
  R: "Runs — times you scored a run",
  BB: "Walks — reached first base via 4 balls",
  K: "Strikeouts — struck out looking or swinging",
  HBP: "Hit By Pitch — reached base after being hit",
  SF: "Sacrifice Fly — fly ball out that scores a runner",
  SB: "Stolen Bases — successfully stole a base",
  CS: "Caught Stealing — thrown out trying to steal",

  AVG: "Batting Average — H / AB. .300+ is good, .400+ is elite",
  OBP: "On-Base Percentage — how often you reach base (H+BB+HBP)/(AB+BB+HBP+SF). .350+ is good",
  SLG: "Slugging — total bases per AB. .450+ is good, .550+ is elite",
  OPS: "On-base Plus Slugging (OBP + SLG). .800+ is good, 1.000+ is elite",
  ISO: "Isolated Power — extra bases per AB (SLG - AVG). Measures raw power",
  BABIP: "Batting Avg on Balls In Play — hit rate excluding HR/K. .300 is league average",
  "BB%": "Walk Rate — BB divided by plate appearances. 8%+ is good",
  "K%": "Strikeout Rate — K divided by plate appearances. Lower is better",
  XBH: "Extra-Base Hits — 2B + 3B + HR",
  CLUTCH: "Clutch Average — batting average with runners in scoring position (RISP_H / RISP)",
  "HARD%": "Hard-Contact Rate — hard-hit balls per AB. 30%+ is good",

  PO: "Putouts — recorded the final out (catch, force, tag)",
  A: "Assists — helped make an out (throw to first, etc.)",
  E: "Errors — fielding mistakes",
  TC: "Total Chances — PO + A + E",
  DP: "Double Plays — participated in a double play",
  "FLD%": "Fielding Percentage — (PO + A) / TC. .950+ is good",
  RF: "Range Factor — (PO + A) per game played. Higher = more range",

  IP: "Innings Pitched",
  ER: "Earned Runs allowed",
  ERA: "Earned Run Average — ER × 9 / IP. Lower is better. Under 3.00 is elite",
  WHIP: "Walks + Hits per Inning Pitched — baserunners allowed per inning. Under 1.20 is elite",
  "K/9": "Strikeouts per 9 innings — 8+ is elite",
  "BB/9": "Walks per 9 innings — lower is better",
  "K/BB": "Strikeout-to-Walk ratio — 2.5+ is elite",
};
